### ISSUE TITLE
Python 2 / 3

### ISSUE THREAD

**Issue by vmasrani** [noahgolmant/skeletor#15]
Nice package! Just a heads up that track is only compatible with python 3, although it will successfully download on python 2. If anyone gets the following error:

`def metric(*, iteration=None, **kwargs):
                ^
SyntaxError: invalid syntax`

Try switching to python 3.

**Comment by noahgolmant** [comment]
Thank you for raising this issue! I am considering trying to make track compatible with python 2 soon before I put it on pypi. Hopefully that's the only issue. It's possible to fix it by replacing `*` with a dummy argument like `__unused=None` but that is a bit messier.

**Comment by noahgolmant** [comment]
Actually, it is a bit messy to make some of the fixes necessary to get things working on python 2 because of other dependencies (e.g. ray), so I'm just going to handle python 3 for now
